In [248]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [249]:
df = pd.read_csv("car_prices.csv")

In [250]:
print(df.shape)

(558837, 16)

In [251]:
df.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [252]:
# Step 1: Determine the top 10 most frequent car makers
top_10_makers = df['make'].value_counts().nlargest(10).index.tolist()

# Step 2: Filter the DataFrame to include only rows with car makers in the top 10
df_filtered = df[df['make'].isin(top_10_makers)]

# Step 3: Drop any remaining rows with missing values
df_filtered.dropna(inplace=True)

# Display the cleaned DataFrame
print(df_filtered.head())

   year    make                model        trim   body transmission  \
0  2015     Kia              Sorento          LX    SUV    automatic
1  2015     Kia              Sorento          LX    SUV    automatic
2  2014     BMW             3 Series  328i SULEV  Sedan    automatic
4  2014     BMW  6 Series Gran Coupe        650i  Sedan    automatic
5  2015  Nissan               Altima       2.5 S  Sedan    automatic

                 vin state  condition  odometer  color interior  \
0  5xyktca69fg566472    ca        5.0   16639.0  white    black
1  5xyktca69fg561319    ca        5.0    9393.0  white    beige
2  wba3c1c51ek116351    ca       45.0    1331.0   gray    black
4  wba6b2c57ed129731    ca       43.0    2641.0   gray    black
5  1n4al3ap1fn326013    ca        1.0    5554.0   gray    black

                                              seller      mmr  sellingprice  \
0                            kia motors america  inc  20500.0       21500.0
1                            kia motors america  inc  20800.0       21500.0
2             financial services remarketing (lease)  31900.0       30000.0
4             financial services remarketing (lease)  66000.0       67000.0
5  enterprise vehicle exchange / tra / rental / t...  15350.0       10900.0

                                  saledate
0  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1  Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2  Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
4  Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
5  Tue Dec 30 2014 12:00:00 GMT-0800 (PST)

C:\Users\shashem1\AppData\Local\Temp\ipykernel_10120\2091094199.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered.dropna(inplace=True)

In [253]:
# correlation_matrix = df_filtered[['sellingprice', 'mmr']].corr()


# unique_models = df_filtered['model'].unique()

# for model in unique_models:
#     model_data = df_filtered[df_filtered['model'] == model]
#     sns.relplot(x='mmr', y='sellingprice', data=model_data, kind='scatter')
#     plt.title(f"Selling Price vs. MMR for {model}")
#     plt.xlabel('MMR')
#     plt.ylabel('Selling Price')
#     plt.show()

In [254]:
print(df_filtered.shape)

(333610, 16)

In [255]:
# Define a function to remove outliers based on residuals
def remove_outliers(model_data):
    # Fit a linear regression model
    lr = LinearRegression()
    X = model_data[['mmr']]
    y = model_data['sellingprice']  # Changed 'selling-price' to 'sellingprice'
    lr.fit(X, y)
    
    # Calculate residuals
    residuals = y - lr.predict(X)
    
    # Define a threshold (e.g., 2 standard deviations)
    threshold = 2 * residuals.std()  # Adjust this threshold as needed
    
    # Remove outliers
    model_data = model_data[abs(residuals) <= threshold]
    
    return model_data

# Create graphs for each unique value of "model"
unique_models = df_filtered['model'].unique()  # Changed 'df' to 'df_filtered'
updated_data = []

for model in unique_models:
    model_data = df_filtered[df_filtered['model'] == model]  # Changed 'df' to 'df_filtered'
    
    # Remove outliers based on residuals
    model_data = remove_outliers(model_data)
    updated_data.append(model_data)
    
    # Plot the graph
    # sns.relplot(x='mmr', y='sellingprice', data=model_data, kind='scatter')  
    # plt.title(f"Selling Price vs. MMR for {model}")
    # plt.xlabel('MMR')
    # plt.ylabel('Selling Price')
    # plt.show()

# Concatenate updated dataframes outside the loop
df_filtered = pd.concat(updated_data, ignore_index=True)

In [256]:
# plt.figure(figsize=(15,5))
# plt.scatter(df_filtered['mmr'],df_filtered['sellingprice'])
# plt.xlabel("Estimated Price")
# plt.ylabel('Selling Price')
# plt.title("Linear relation between mmr and selling price")
# plt.tight_layout()
# plt.show()

In [257]:
print(df_filtered["make"].unique())

['Kia' 'BMW' 'Nissan' 'Chevrolet' 'Ford' 'Hyundai' 'Toyota' 'Dodge'
 'Chrysler' 'Honda']

In [258]:
print(df_filtered["make"].value_counts())

make
Ford         78458
Chevrolet    52085
Nissan       42108
Toyota       33955
Dodge        26120
Honda        23826
Hyundai      17834
BMW          16817
Kia          15118
Chrysler     14520
Name: count, dtype: int64

In [259]:
print(df_filtered.shape)

(320841, 16)

In [260]:
# Assuming 'make' and 'model' are columns in your DataFrame 'df_filtered'
unique_makes = df_filtered['make'].unique()

for make in unique_makes:
    models_for_make = df_filtered[df_filtered['make'] == make]['model'].unique()
    print(f"{make}: {models_for_make}")

Kia: ['Sorento' 'Optima' 'K900' 'Rio' 'Soul' 'Forte' 'Sportage' 'Sedona'
 'Spectra' 'Rondo' 'Borrego' 'Cadenza' 'Amanti' 'Sephia']
BMW: ['3 Series' '6 Series Gran Coupe' 'M5' '6 Series' '5 Series' 'X6' 'X1'
 '4 Series' 'X5' '7 Series' '1 Series' 'M3' 'X3' 'Z4' 'X5 M'
 '5 Series Gran Turismo' 'X6 M' 'Z3' 'M' 'M4' 'ActiveHybrid X6' 'M6'
 '2 Series' 'M6 Gran Coupe' '3 Series Gran Turismo' 'ActiveHybrid 7'
 'Z4 M' 'i8' 'ActiveHybrid 5' 'X4' '4 Series Gran Coupe']
Nissan: ['Altima' 'Versa' 'Versa Note' '370Z' 'Juke' 'NV' 'Leaf' 'NV200' 'Rogue'
 'Maxima' 'Xterra' 'Sentra' 'Frontier' 'Cube' 'Armada' 'Pathfinder'
 'Murano' 'GT-R' 'Altima Hybrid' '350Z' 'Titan' 'Quest' 'Rogue Select'
 'Truck' 'Murano CrossCabriolet' '200SX' 'NV Cargo' 'NV Passenger' '300ZX']
Chevrolet: ['Cruze' 'Camaro' 'Impala' 'Suburban' 'Malibu' 'Silverado 1500' 'Traverse'
 'Silverado 2500HD' 'Equinox' 'Captiva Sport' 'Volt' 'Express Cargo'
 'Colorado' 'Express' 'Sonic' 'HHR' 'Tahoe' 'Impala Limited' 'Aveo'
 'Corvette' 'malibu' 'Avalanche' 'Tahoe Hybrid' 'Malibu Classic' 'Cobalt'
 'Uplander' 'Silverado 1500 Classic' 'Monte Carlo' 'TrailBlazer'
 'Malibu Maxx' 'Blazer' 'Cavalier' 'Venture' 'S-10' 'Silverado 1500HD'
 'Spark' 'SSR' 'Silverado 3500HD' 'Silverado 1500 Hybrid'
 'Silverado 2500HD Classic' 'Silverado 3500' 'TrailBlazer EXT' 'Classic'
 'Silverado 2500' 'Tracker' 'Prizm' 'Astro' 'Tahoe Limited/Z71'
 'C/K 1500 Series' 'Lumina' 'Black Diamond Avalanche' 'Corvette Stingray'
 'SS' 'Astro Cargo' 'Malibu Hybrid' 'C/K 3500 Series' 'Caprice'
 'C/K 2500 Series' 'Silverado 3500 Classic' 'S-10 Blazer' 'Spark EV']
Ford: ['Fusion' 'Escape' 'Edge' 'Focus' 'F-350 Super Duty' 'Fiesta' 'Flex'
 'Explorer' 'F-150' 'E-Series Van' 'E-Series Wagon' 'Expedition' 'Mustang'
 'Transit Connect' 'Taurus' 'Escape Hybrid' 'Ranger' 'Fusion Hybrid'
 'F-250 Super Duty' 'Econoline Cargo' 'Econoline Wagon' 'F-450 Super Duty'
 'Explorer Sport Trac' 'Five Hundred' 'Freestyle' 'Freestar' 'Excursion'
 'Thunderbird' 'Contour' 'Escort' 'Mustang SVT Cobra' 'Shelby GT500'
 'C-Max Energi' 'C-Max Hybrid' 'Crown Victoria' 'Taurus X' 'Expedition EL'
 'Focus ST' 'Fusion Energi' 'F-150 Heritage' 'Explorer Sport' 'Windstar'
 'Tempo' 'Windstar Cargo' 'F-150 SVT Lightning' 'E-150' 'Aspire'
 'Transit Van' 'E-250' 'Transit Wagon']
Hyundai: ['Elantra' 'Santa Fe' 'Genesis' 'Equus' 'Sonata' 'Sonata Hybrid' 'Accent'
 'Veloster' 'Elantra Coupe' 'Azera' 'Tucson' 'Genesis Coupe' 'Veracruz'
 'Santa Fe Sport' 'Elantra GT' 'Elantra Touring' 'Tiburon' 'Entourage'
 'XG350' 'XG300']
Toyota: ['Corolla' 'Sienna' 'Yaris' 'Camry' 'Tacoma' 'FJ Cruiser' 'Avalon'
 'Tundra' 'Prius' 'Camry Hybrid' '4Runner' 'Sequoia' 'Venza' 'Highlander'
 'Highlander Hybrid' 'RAV4' 'Prius Plug-in' 'Land Cruiser' 'Camry Solara'
 'Celica' 'Matrix' 'Prius v' 'Tercel' 'Prius c' 'ECHO' 'MR2 Spyder'
 'Pickup' 'Avalon Hybrid' 'T100']
Dodge: ['Avenger' 'Journey' 'Charger' 'Grand Caravan' 'Nitro' 'Challenger' 'Dart'
 'Caliber' 'Magnum' 'Durango' 'Ram Pickup 1500' 'Sprinter Cargo' 'Dakota'
 'Neon' 'Stratus' 'Ram Pickup 3500' 'Intrepid' 'Ram Pickup 2500' 'Caravan'
 'Ram Cargo' 'Viper' 'Sprinter']
Chrysler: ['200' '300' 'Town and Country' 'Sebring' 'PT Cruiser' 'Pacifica'
 'Concorde' 'LHS' 'Aspen' 'Crossfire' '300M' 'Prowler' 'Cirrus' 'Voyager']
Honda: ['Accord' 'CR-V' 'Civic' 'Fit' 'Pilot' 'Odyssey' 'Crosstour' 'CR-Z'
 'Accord Crosstour' 'Insight' 'Ridgeline' 'S2000' 'Element' 'accord'
 'Passport' 'Prelude' 'Accord Hybrid']

In [261]:
# Import pandas library
import pandas as pd

# Assuming 'make' and 'model' are columns in your DataFrame 'df_filtered'
# Initialize an empty list to store filtered DataFrames
dfs = []

# Group the DataFrame by 'make'
grouped = df_filtered.groupby('make')

# Iterate over each group
for make, group_df in grouped:
    # Sort the group by the count of models in descending order
    sorted_group = group_df['model'].value_counts().sort_values(ascending=False)
    # Get the top 5 models with the most data points
    top3_models = sorted_group.head(3).index.tolist()
    # Filter the original DataFrame for the top 5 models of the current make
    filtered_group = group_df[group_df['model'].isin(top3_models)]
    # Append the filtered group to the list
    dfs.append(filtered_group)

# Concatenate all filtered DataFrames into one DataFrame
df_filtered = pd.concat(dfs)

# Displaying the filtered DataFrame
print(df_filtered)

        year    make     model        trim         body transmission  \
2759    2014     BMW  3 Series  328i SULEV        Sedan    automatic
2760    2014     BMW  3 Series  328i SULEV        Sedan    automatic
2761    2014     BMW  3 Series  328i SULEV        Sedan    automatic
2762    2012     BMW  3 Series       335is  Convertible    automatic
2763    2012     BMW  3 Series        328i  Convertible    automatic
...      ...     ...       ...         ...          ...          ...
283131  2014  Toyota      RAV4     Limited          suv    automatic
283132  1999  Toyota      RAV4        Base          suv    automatic
283133  2012  Toyota      RAV4     Limited          suv    automatic
283134  2007  Toyota      RAV4        Base          suv    automatic
283135  2007  Toyota      RAV4        Base          suv    automatic

                      vin state  condition  odometer  color interior  \
2759    wba3c1c51ek116351    ca       45.0    1331.0   gray    black
2760    wba3c1c50ek108497    ca        5.0     111.0  black        —
2761    wba3c1c58ek106688    ca       45.0    9027.0  white    black
2762    wbadx1c56ce570700    ca       38.0   14149.0  black    black
2763    wbadw7c5xce729000    ca       31.0   27675.0   blue     gray
...                   ...   ...        ...       ...    ...      ...
283131  2t3dfrevxew135286    pa       46.0   23467.0  white    black
283132  jt3gp10v2x0036850    ma        2.0  131468.0   blue     gray
283133  2t3df4dv5cw205696    pa       41.0   30119.0  black     gray
283134  jtmbd35v875121181    nv       35.0   93696.0   gold    beige
283135  jtmzd33v075038734    fl       34.0   55692.0    red    beige

                                        seller      mmr  sellingprice  \
2759    financial services remarketing (lease)  31900.0       30000.0
2760    financial services remarketing (lease)  32200.0       30500.0
2761    financial services remarketing (lease)  30200.0       27500.0
2762    financial services remarketing (lease)  39900.0       40500.0
2763    financial services remarketing (lease)  28200.0       25750.0
...                                        ...      ...           ...
283131                         manheim imports  24800.0       24700.0
283132                 boch toyota/scion south   1700.0        2200.0
283133            r hollenshead auto sales inc  18850.0       19000.0
283134                     bul connections llc   7550.0        9200.0
283135                          metro ford inc   9775.0        9700.0

                                       saledate
2759    Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
2760    Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
2761    Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
2762    Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
2763    Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
...                                         ...
283131  Fri Jun 19 2015 02:00:00 GMT-0700 (PDT)
283132  Thu Jun 18 2015 11:30:00 GMT-0700 (PDT)
283133  Fri Jun 19 2015 02:00:00 GMT-0700 (PDT)
283134  Fri Jun 19 2015 04:45:00 GMT-0700 (PDT)
283135  Fri Jun 19 2015 02:30:00 GMT-0700 (PDT)

[174232 rows x 16 columns]

In [262]:
# Extracting the date and time part from the 'saledate' column
df_filtered['saledate_clean'] = df_filtered['saledate'].str.split(' ').str[:5].str.join(' ')

# Converting the cleaned saledate to datetime format
df_filtered['saledate_clean'] = pd.to_datetime(df_filtered['saledate_clean'], format='%a %b %d %Y %H:%M:%S')

# Extracting the year from the cleaned 'saledate' column
df_filtered['saledate_year'] = df_filtered['saledate_clean'].dt.year

# Calculating the age of the vehicle
df_filtered['age'] = df_filtered['saledate_year'] - df_filtered['year']

# Dropping intermediate columns
df_filtered.drop(columns=['saledate_clean', 'saledate_year'], inplace=True)

# Displaying the DataFrame with the new 'age' column
print(df_filtered)

        year    make     model        trim         body transmission  \
2759    2014     BMW  3 Series  328i SULEV        Sedan    automatic
2760    2014     BMW  3 Series  328i SULEV        Sedan    automatic
2761    2014     BMW  3 Series  328i SULEV        Sedan    automatic
2762    2012     BMW  3 Series       335is  Convertible    automatic
2763    2012     BMW  3 Series        328i  Convertible    automatic
...      ...     ...       ...         ...          ...          ...
283131  2014  Toyota      RAV4     Limited          suv    automatic
283132  1999  Toyota      RAV4        Base          suv    automatic
283133  2012  Toyota      RAV4     Limited          suv    automatic
283134  2007  Toyota      RAV4        Base          suv    automatic
283135  2007  Toyota      RAV4        Base          suv    automatic

                      vin state  condition  odometer  color interior  \
2759    wba3c1c51ek116351    ca       45.0    1331.0   gray    black
2760    wba3c1c50ek108497    ca        5.0     111.0  black        —
2761    wba3c1c58ek106688    ca       45.0    9027.0  white    black
2762    wbadx1c56ce570700    ca       38.0   14149.0  black    black
2763    wbadw7c5xce729000    ca       31.0   27675.0   blue     gray
...                   ...   ...        ...       ...    ...      ...
283131  2t3dfrevxew135286    pa       46.0   23467.0  white    black
283132  jt3gp10v2x0036850    ma        2.0  131468.0   blue     gray
283133  2t3df4dv5cw205696    pa       41.0   30119.0  black     gray
283134  jtmbd35v875121181    nv       35.0   93696.0   gold    beige
283135  jtmzd33v075038734    fl       34.0   55692.0    red    beige

                                        seller      mmr  sellingprice  \
2759    financial services remarketing (lease)  31900.0       30000.0
2760    financial services remarketing (lease)  32200.0       30500.0
2761    financial services remarketing (lease)  30200.0       27500.0
2762    financial services remarketing (lease)  39900.0       40500.0
2763    financial services remarketing (lease)  28200.0       25750.0
...                                        ...      ...           ...
283131                         manheim imports  24800.0       24700.0
283132                 boch toyota/scion south   1700.0        2200.0
283133            r hollenshead auto sales inc  18850.0       19000.0
283134                     bul connections llc   7550.0        9200.0
283135                          metro ford inc   9775.0        9700.0

                                       saledate  age
2759    Thu Jan 15 2015 04:30:00 GMT-0800 (PST)    1
2760    Thu Jan 15 2015 04:30:00 GMT-0800 (PST)    1
2761    Thu Jan 15 2015 04:30:00 GMT-0800 (PST)    1
2762    Thu Dec 18 2014 12:30:00 GMT-0800 (PST)    2
2763    Thu Jan 29 2015 04:30:00 GMT-0800 (PST)    3
...                                         ...  ...
283131  Fri Jun 19 2015 02:00:00 GMT-0700 (PDT)    1
283132  Thu Jun 18 2015 11:30:00 GMT-0700 (PDT)   16
283133  Fri Jun 19 2015 02:00:00 GMT-0700 (PDT)    3
283134  Fri Jun 19 2015 04:45:00 GMT-0700 (PDT)    8
283135  Fri Jun 19 2015 02:30:00 GMT-0700 (PDT)    8

[174232 rows x 17 columns]

In [263]:
# Assuming 'make' and 'model' are columns in your DataFrame 'df_filtered'
unique_makes = df_filtered['make'].unique()

for make in unique_makes:
    models_for_make = df_filtered[df_filtered['make'] == make]['model'].unique()
    print(f"{make}: {models_for_make}")

BMW: ['3 Series' '5 Series' 'X5']
Chevrolet: ['Impala' 'Malibu' 'Silverado 1500']
Chrysler: ['200' '300' 'Town and Country']
Dodge: ['Avenger' 'Charger' 'Grand Caravan']
Ford: ['Fusion' 'Escape' 'F-150']
Honda: ['Accord' 'Civic' 'Odyssey']
Hyundai: ['Elantra' 'Sonata' 'Accent']
Kia: ['Sorento' 'Optima' 'Forte']
Nissan: ['Altima' 'Maxima' 'Sentra']
Toyota: ['Corolla' 'Camry' 'RAV4']

In [264]:
df_filtered = df_filtered.drop(columns=['body', 'trim', 'vin', 'seller', 'mmr', 'saledate', 'state','interior','color'])

df_filtered.head()

      year make     model transmission  condition  odometer  sellingprice  age
2759  2014  BMW  3 Series    automatic       45.0    1331.0       30000.0    1
2760  2014  BMW  3 Series    automatic        5.0     111.0       30500.0    1
2761  2014  BMW  3 Series    automatic       45.0    9027.0       27500.0    1
2762  2012  BMW  3 Series    automatic       38.0   14149.0       40500.0    2
2763  2012  BMW  3 Series    automatic       31.0   27675.0       25750.0    3

In [265]:
print(df_filtered.shape)

(174232, 8)

In [266]:
df_filtered = df_filtered.apply(lambda x: x.str.upper() if x.dtype == "object" else x)  
df_filtered = df_filtered.dropna(how='any', axis=0)

In [267]:
print(df_filtered.shape)

(174232, 8)

In [268]:
print(df_filtered["make"].value_counts())

make
FORD         33795
NISSAN       24877
TOYOTA       20025
CHEVROLET    18684
HONDA        17899
DODGE        14202
HYUNDAI      12346
BMW          12048
CHRYSLER     11622
KIA           8734
Name: count, dtype: int64

In [269]:
df_filtered.head()

      year make     model transmission  condition  odometer  sellingprice  age
2759  2014  BMW  3 SERIES    AUTOMATIC       45.0    1331.0       30000.0    1
2760  2014  BMW  3 SERIES    AUTOMATIC        5.0     111.0       30500.0    1
2761  2014  BMW  3 SERIES    AUTOMATIC       45.0    9027.0       27500.0    1
2762  2012  BMW  3 SERIES    AUTOMATIC       38.0   14149.0       40500.0    2
2763  2012  BMW  3 SERIES    AUTOMATIC       31.0   27675.0       25750.0    3

In [270]:
memory_kb = df_filtered.memory_usage(deep=True).sum() / 1024
print("Memory usage:", memory_kb, "KB")

Memory usage: 40875.4716796875 KB

In [271]:
#encoder
le_make = LabelEncoder()
df_filtered["make"] = le_make.fit_transform(df_filtered["make"])
le_model = LabelEncoder()
df_filtered["model"] = le_model.fit_transform(df_filtered["model"])
# le_color = LabelEncoder()
# df_filtered["color"] = le_color.fit_transform(df_filtered["color"])
# le_interior = LabelEncoder()
# df_filtered["interior"] = le_interior.fit_transform(df_filtered["interior"])
le_transmission = LabelEncoder()
df_filtered["transmission"] = le_transmission.fit_transform(df_filtered["transmission"])

In [272]:
df_filtered.head()

      year  make  model  transmission  condition  odometer  sellingprice  age
2759  2014     0      1             0       45.0    1331.0       30000.0    1
2760  2014     0      1             0        5.0     111.0       30500.0    1
2761  2014     0      1             0       45.0    9027.0       27500.0    1
2762  2012     0      1             0       38.0   14149.0       40500.0    2
2763  2012     0      1             0       31.0   27675.0       25750.0    3

In [273]:
X = df_filtered.drop("sellingprice", axis=1)
y = df_filtered["sellingprice"]

In [274]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import sys

X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y, test_size=0.3, 
    random_state=10
)
# Initialize and train the model
rf_reg = RandomForestRegressor(n_estimators=100, random_state=10)
rf_reg.fit(X_train, y_train)

# Get the size of the regressor object
regressor_size_kb = sys.getsizeof(rf_reg) / 1024  # Convert bytes to kilobytes

print("Regressor size:", round(regressor_size_kb, 2), "KB")

print("Feature Importances:", rf_reg.feature_importances_)

print("train score: ", round(rf_reg.score(X_train, y_train) * 100, 2), "%")
print("test score: ", round(rf_reg.score(X_test, y_test) * 100, 2), "%")

# Make predictions
y_train_pred = rf_reg.predict(X_train)
y_test_pred = rf_reg.predict(X_test)

# Evaluate the model
train_rmse = mean_squared_error(y_train, y_train_pred, squared=False)
test_rmse = mean_squared_error(y_test, y_test_pred, squared=False)

print("Train RMSE:", train_rmse)
print("Test RMSE:", test_rmse)

Regressor size: 0.05 KB
Feature Importances: [0.12171683 0.1698896  0.1806528  0.00068056 0.0349306  0.48018665
 0.01194297]
train score:  98.58 %
test score:  89.98 %
Train RMSE: 826.4134794646358
Test RMSE: 2166.5174631299788

In [275]:
# from sklearn.tree import DecisionTreeRegressor
# from sklearn.metrics import mean_squared_error

# # Instantiate the Decision Tree model
# dt_regressor = DecisionTreeRegressor(random_state=10)

# # Train the model
# dt_regressor.fit(X_train, y_train)

# # Make predictions
# train_predictions = dt_regressor.predict(X_train)
# test_predictions = dt_regressor.predict(X_test)

# # Calculate RMSE
# train_rmse = mean_squared_error(y_train, train_predictions, squared=False)
# test_rmse = mean_squared_error(y_test, test_predictions, squared=False)

# #print("Shape of reg coefficients:", dt_regressor.coef_.shape)
# print("Feature Importances:", dt_regressor.feature_importances_)
# print("train score: ", round(dt_regressor.score(X_train, y_train) * 100, 2), "%")
# print("test score: ", round(dt_regressor.score(X_test, y_test) * 100, 2), "%")


# print("Train RMSE:", train_rmse)
# print("Test RMSE:", test_rmse)

In [276]:
import joblib

data = {"rf_reg": rf_reg, "make": le_make, "model": le_model, "transmission": le_transmission}
joblib.dump(data, 'saved_model3.pkl')

['saved_model3.pkl']

In [277]:
import sklearn
print(sklearn.__version__)

1.2.2

In [278]:
# import pickle
# data = {"rf_reg": rf_reg, "make": le_make, "model": le_model, "color": le_color, "interior": le_interior, "transmission": le_transmission}
# with open('saved_model.pkl', 'wb') as file:
#     pickle.dump(data, file)